backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "males"
    label: "Male Dogs"
    folder: "src/content/dogs/males"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Long Alias Heading", name: "longAlias", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Weight (lbs)", name: "weight", widget: "number" }
      - { label: "Head Size (inches)", name: "headSize", widget: "number" }
      - { label: "Height (inches)", name: "height", widget: "number" }
      - { label: "Still Growing", name: "stillGrowing", widget: "boolean", default: false }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "females"
    label: "Female Dogs"
    folder: "src/content/dogs/females"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Long Alias Heading", name: "longAlias", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Weight (lbs)", name: "weight", widget: "number" }
      - { label: "Head Size (inches)", name: "headSize", widget: "number" }
      - { label: "Height (inches)", name: "height", widget: "number" }
      - { label: "Still Growing", name: "stillGrowing", widget: "boolean", default: false }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "breedings"
    label: "Breedings"
    folder: "src/content/breedings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Father", name: "father", widget: "relation", collection: "males", search_fields: ["name"], value_field: "{{slug}}", display_fields: ["name"] }
      - { label: "Mother", name: "mother", widget: "relation", collection: "females", search_fields: ["name"], value_field: "{{slug}}", display_fields: ["name"] }
      - { label: "Father Image", name: "fatherImage", widget: "image" }
      - { label: "Mother Image", name: "motherImage", widget: "image" }
      - { label: "1st Male Price", name: "firstMalePrice", widget: "number" }
      - { label: "2nd Male Price", name: "secondMalePrice", widget: "number" }
      - { label: "3rd Male Price", name: "thirdMalePrice", widget: "number" }
      - { label: "1st Female Price", name: "firstFemalePrice", widget: "number" }
      - { label: "2nd Female Price", name: "secondFemalePrice", widget: "number" }
      - { label: "3rd Female Price", name: "thirdFemalePrice", widget: "number" }
      - { label: "1st Male Sold", name: "firstMaleSold", widget: "boolean", default: false }
      - { label: "2nd Male Sold", name: "secondMaleSold", widget: "boolean", default: false }
      - { label: "3rd Male Sold", name: "thirdMaleSold", widget: "boolean", default: false }
      - { label: "1st Female Sold", name: "firstFemaleSold", widget: "boolean", default: false }
      - { label: "2nd Female Sold", name: "secondFemaleSold", widget: "boolean", default: false }
      - { label: "3rd Female Sold", name: "thirdFemaleSold", widget: "boolean", default: false }
      - { label: "Description", name: "body", widget: "markdown" } 